SystemOrganization addCategory: #'Moose-Camel'!
SystemOrganization addCategory: 'Moose-Camel-AST - Dependencies'!
SystemOrganization addCategory: 'Moose-Camel-AST - Nodes'!
SystemOrganization addCategory: 'Moose-Camel-AST - Visitor'!
SystemOrganization addCategory: 'Moose-Camel-CoreNLP'!
SystemOrganization addCategory: 'Moose-Camel-Distance'!
SystemOrganization addCategory: 'Moose-Camel-Examples'!
SystemOrganization addCategory: 'Moose-Camel-Grammar'!
SystemOrganization addCategory: 'Moose-Camel-Query - Model'!
SystemOrganization addCategory: 'Moose-Camel-Spotter'!
