language: smalltalk
sudo: true

dist: trusty

os:
  - linux

smalltalk:
  - Moose-6.1
             
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig/;
      
      echo "Installing c++ libraries";
      sudo apt-get install libstdc++6:i386;
      
      echo "Installing libssl1.0.0...";
      sudo apt-get install libssl1.0.0:i386;
      
      echo "Installing libGL...";
      sudo apt-get install libglu1-mesa:i386;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi
