as yet unclassified
frequentlyAskedQuestions
	
	^ 'What are the deprecated classes
What are the deprecated methods
find method of name length
Where are occurences of type Integer
Where is the declaration of type Foo
Where are occurences of package blubb
Where are declarations of package blubb
Where are occurences of constructor Foo
Where are declarations of constructor Foo
Where are occurences of field number
Where is the declaration of number
Where are references to field number
Where are settings of field number
Where are imports of type List
Where are subtypes of Foo
Where are subclasses of Foo
Where are type arguments of type String
Which methods take an argument of type Foo
What throws exceptions of type NullPointerException
What catches exceptions of type NullPointerException
Which methods return type Foo
Where are calls to foo from a this reference
Where are String type arguments
Where are instance creations of type Foo
Where are declarations of local variables of type Integer
Which classes have Foo as supertype
Where are NullPointerException thrown
Where are NullPointerException catched
Which classes are subclasses of Foo
where is the method init called'	